//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relations
    {
        public int id { get; set; }
        public Nullable<int> segment_ID { get; set; }
        public int relation1 { get; set; }
        public int relation2 { get; set; }
    
        public virtual segments segments { get; set; }
    }
}
