//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeometryTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class angles
    {
        public int id { get; set; }
        public int segment1 { get; set; }
        public int segment2 { get; set; }
    
        public virtual segments segments { get; set; }
        public virtual segments segments1 { get; set; }
    }
}
